apiVersion: v1
kind: ServiceAccount
metadata:
  name: ronin-forecast-orchestrator-account
  namespace: ronin
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: job-manager
  namespace: ronin
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: job-manager-binding
  namespace: ronin
subjects:
  - kind: ServiceAccount
    name: ronin-forecast-orchestrator-account
    namespace: ronin
roleRef:
  kind: Role
  name: job-manager
  apiGroup: rbac.authorization.k8s.io