---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ronin-frontend
  labels:
    app.kubernetes.io/name: ronin-frontend
    app.kubernetes.io/instance: ronin-frontend
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: ronin-frontend
      app.kubernetes.io/instance: ronin-frontend
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ronin-frontend
        app.kubernetes.io/instance: ronin-frontend
    spec:
      containers:
      - name: ronin-frontend
        image: ghcr.io/ronin-cg/frontend:1.0.28
        imagePullPolicy: IfNotPresent
        ports:
          - name: http
            containerPort: 80
            protocol: TCP
        readinessProbe:
          httpGet:
            path: /api/zhealth
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /api/zhealth
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 3
        env:
          - name: ADMIN_API_KEY
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: ADMIN_API_KEY
          - name: AMAZON_APP_ID
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: AMAZON_APP_ID
          - name: AMAZON_CLIENT_ID
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: AMAZON_CLIENT_ID
          - name: AMAZON_CLIENT_SECRET
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: AMAZON_CLIENT_SECRET
          - name: BETTER_AUTH_SECRET
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: BETTER_AUTH_SECRET
          - name: APP_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: APP_DATABASE_URL
          - name: AUTH_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: AUTH_DATABASE_URL
          - name: LAKE_DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: LAKE_DATABASE_URL
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: AWS_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: AWS_SECRET_ACCESS_KEY
          - name: RESEND_API_KEY
            valueFrom:
              secretKeyRef:
                name: ronin-frontend-secrets
                key: RESEND_API_KEY
        envFrom:
          - configMapRef:
              name: ronin-frontend-configs
      imagePullSecrets:
        - name: ghcr-login-secret
---
apiVersion: v1
kind: Service
metadata:
  name: ronin-frontend
  labels:
    app.kubernetes.io/name: ronin-frontend
spec:
  selector:
    app.kubernetes.io/name: ronin-frontend
    app.kubernetes.io/instance: ronin-frontend
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 80
